export const tagConverter = {
  golf: "⛳️",
  fishing: "🎣",
  tennis: "🎾",
  arthistory: "🎨",
  musictheory: "🎵",
  programming: "💻",
  basketball: "🏀",
  americanfootball: "🏈",
  videogames: "🎮",
  chess: "♟",
  soccer: "⚽️",
  baseball: "⚾️",
  volleyball: "🏐",
  hockey: "🏒",
  skiing: "⛷",
  snowboarding: "🏂",
  surfing: "🏄",
  swimming: "🏊",
  endurancesports: "🏃",
  martialarts: "🥋",
  dance: "💃",
  cooking: "🍳",
  knitting: "🧶",
  movieproduction: "🎥",
  classicrock: "🎸",
  musicals: "🎭",
  classicalmusic: "🎻",
  computerhardware: "💻",
  operatingsystems: "operating systems",
  geometry: "📐",
  calculus: "📈",
  architecture: "🏛",
  chemistry: "🧪",
  astronomy: "🔭",
  rollercoasters: "🎢",
  quantummechanics: "quantum mechanics",
  astrophysics: "🪐",
  spongebobsquarepants: "🧽",
  futurama: "🤖",
  thesimpsons: "🍩",
  starwars: "star wars",
  startrek: "star trek",
  harrypotter: "⚡️",
  lordoftherings: "🧙",
  avengers: "🦸",
  phineasandferb: "phineas and ferb",
  theoffice: "the office",
  rickandmorty: "rick and morty",
  thematrix: "the matrix",
  hiphop: "🎤",
};
